services:

# -------------------------
# AUTH SERVICE
# -------------------------
  auth-service:
    build: ./services/auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    environment:
      AUTH_SERVICE_API_KEY: auth-service-api-key-2024

  auth-db:
    image: mongo
    container_name: auth-db
    ports:
      - "27021:27017"
  # -------------------------
  # PATIENT SERVICE
  # -------------------------
  patient-service:
    build: ./services/patient-service
    ports:
      - "4001:4001"
    env_file:
      - ./services/patient-service/.env
    environment:
      AUTH_SERVICE_URL: http://auth-service:5000
      AUTH_SERVICE_API_KEY: auth-service-api-key-2024
      APPOINTMENT_SERVICE_URL: http://appointment-service:4003
      DOCTOR_SERVICE_URL: http://doctor-service:4002
      TELEMEDICINE_SERVICE_URL: http://telemedicine-service:4004
      NOTIFICATION_SERVICE_URL: http://notification-service:4006
      NOTIFICATION_SERVICE_API_KEY: notification-service-api-key-2024
    depends_on:
      - patient-db
      - auth-service
      - notification-service

  patient-db:
    image: mongo
    container_name: patient-db
    ports:
      - "27017:27017"

  # -------------------------
  # DOCTOR SERVICE
  # -------------------------
  doctor-service:
    build: ./services/doctor-service
    ports:
      - "4002:4002"
    env_file:
      - ./services/doctor-service/.env
    environment:
      APPOINTMENT_SERVICE_URL: http://appointment-service:4003
      PATIENT_SERVICE_URL: http://patient-service:4001
      TELEMEDICINE_SERVICE_URL: http://telemedicine-service:4004
    depends_on:
      - doctor-db

  doctor-db:
    image: mongo
    container_name: doctor-db
    ports:
      - "27018:27017"

  # -------------------------
  # APPOINTMENT SERVICE
  # -------------------------
  appointment-service:
    build: ./services/appointment-service
    ports:
      - "4003:4003"
    env_file:
      - ./services/appointment-service/.env
    depends_on:
      - appointment-db

  appointment-db:
    image: mongo
    container_name: appointment-db
    ports:
      - "27019:27017"

  # -------------------------
  # TELEMEDICINE SERVICE
  # -------------------------
  telemedicine-service:
    build: ./services/telemedicine-service
    ports:
      - "4004:4004"
    env_file:
      - ./services/telemedicine-service/.env
    depends_on:
      - appointment-service
      - auth-service
      - notification-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:5000
      AUTH_SERVICE_API_KEY: auth-service-api-key-2024
      APPOINTMENT_SERVICE_URL: http://appointment-service:4003
      NOTIFICATION_SERVICE_URL: http://notification-service:4006
      NOTIFICATION_SERVICE_API_KEY: notification-service-api-key-2024

  # -------------------------
  # PAYMENT SERVICE
  # -------------------------
  payment-service:
    build: ./services/payment-service
    ports:
      - "4005:4005"
    env_file:
      - ./services/payment-service/.env
    depends_on:
      - payment-db

  payment-db:
    image: mongo
    container_name: payment-db
    ports:
      - "27020:27017"

  # -------------------------
  # NOTIFICATION SERVICE
  # -------------------------
  notification-service:
    build: ./services/notification-service
    ports:
      - "4006:4006"
    env_file:
      - ./services/notification-service/.env



# -------------------------
# FRONTEND (FIXED - IMPORTANT)
# -------------------------
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - appointment-service
    environment:
      - HOST=0.0.0.0
      - PORT=5173
      - AUTH_SERVICE_URL=http://auth-service:5000
      - PATIENT_SERVICE_URL=http://patient-service:4001
      - DOCTOR_SERVICE_URL=http://doctor-service:4002
      - APPOINTMENT_SERVICE_URL=http://appointment-service:4003
      - TELEMEDICINE_SERVICE_URL=http://telemedicine-service:4004
      - PAYMENT_SERVICE_URL=http://payment-service:4005
      - NOTIFICATION_SERVICE_URL=http://notification-service:4006
