apiVersion: v1
kind: Secret
metadata:
  name: telemedicine-secrets
  namespace: telemedicine
type: Opaque
stringData:
  AUTH_MONGO_URI: "mongodb+srv://pixelbluegfx_db_user:0Bde1VOqbc6K50p1@ds.rxxios9.mongodb.net/auth_db?retryWrites=true&w=majority"
  AUTH_JWT_SECRET: "secret123"
  APPOINTMENT_MONGO_URI: "mongodb+srv://Arosh2:it70412@cluster0.5o2had0.mongodb.net/?appName=Cluster0"
  PATIENT_MONGODB_URI: "mongodb+srv://year3semester1project_db_user:biB6vRRGLpQAcSJ6@patient.b4f55ov.mongodb.net/?appName=Patient"
  DOCTOR_MONGODB_URI: "mongodb+srv://year3semester1project_db_user:TM7ZijJZLax9al5i@doctor.il3csmg.mongodb.net/?appName=Doctor"
  TELEMEDICINE_MONGODB_URI: "mongodb+srv://abc:abc123abc@cluster1.cyhpeey.mongodb.net/?appName=Cluster1"
  PAYMENT_MONGODB_URI: "mongodb+srv://year3semester1project_db_user:ThgiJLDPVPRgyO0h@payment.xuxzdgh.mongodb.net/?appName=Payment"
  NOTIFICATION_MONGODB_URI: "mongodb+srv://Arosh2:it70412@cluster0.5o2had0.mongodb.net/?appName=Cluster0"
  AUTH_SERVICE_API_KEY: "auth-service-api-key-2024"
  NOTIFICATION_SERVICE_API_KEY: "notification-service-api-key-2024"
  BREVO_API_KEY: "test_brevo_api_key_2024"
  BREVO_SENDER_EMAIL: "year3semester1project@gmail.com"
  BREVO_SENDER_NAME: "Ceylon MediHub"
  BOLDSIGN_API_KEY: "test_boldsign_api_key_2024"
